const pdfModel = {};

pdfModel.bimeh = [
    { id: "fullName"        , value: "نام و نام خانوادگی"   , x: 170    , y: 40 },
    { id: "fatherName"      , value: "نام پدر"              , x: 120    , y: 40 },
    { id: "shNum"           , value: "شماره شناسنامه"       , x: 72     , y: 40 },
    { id: "meliCode"        , value: "کد ملی"               , x: 47     , y: 40 },
    { id: "birthdayDate"    , value: "تاریخ تولد"           , x: 180    , y: 46 },
    { id: "birthdayPlace"   , value: "محل تولد"             , x: 133    , y: 46 },
    { id: "birthdayIssue"   , value: "محل صدور"             , x: 88     , y: 46 },
    { id: "retCode"         , value: "شماره پرسنلی"         , x: 35     , y: 46 },
    { id: "cost"            , value: "هزینه فرد"            , x: 175    , y: 53 },
    { id: "resBank"         , value: "حساب رسالت"           , x: 110    , y: 53 },
    { id: "workPlace"       , value: "محل خدمت"             , x: 55     , y: 53 },
    { id: "address"         , value: "آدرس محل سکونت"       , x: 170    , y: 62 },
    { id: "phoneNumber"     , value: "تلفن همراه"           , x: 45     , y: 62 },
    { id: "totalCost"       , value: "مبلغ کل"              , x: 140    , y: 247},
    { id: "signDate"        , value: "تاریخ امضا"           , x: 180    , y: 247},

    { id: "fullName1"       , value: "نام و نام خانوادگی"   , x: 187    , y: 190},
    { id: "sponsorship1"    , value: "بلی"                  , x: 155    , y: 190},
    { id: "meliCode1"       , value: "کد ملی"               , x: 145    , y: 190},
    { id: "fatherName1"     , value: "نام پدر"              , x: 122    , y: 190},
    { id: "birthdayDate1"   , value: "تاریخ تولد"           , x: 110    , y: 190},
    { id: "relation1"       , value: "نسبت"                 , x: 75     , y: 190},
    { id: "cost1"           , value: "هزینه فرد"            , x: 33     , y: 190},

    { id: "fullName2"       , value: "نام و نام خانوادگی"   , x: 187    , y: 198},
    { id: "sponsorship2"    , value: "بلی"                  , x: 155    , y: 198},
    { id: "meliCode2"       , value: "کد ملی"               , x: 145    , y: 198},
    { id: "fatherName2"     , value: "نام پدر"              , x: 122    , y: 198},
    { id: "birthdayDate2"   , value: "تاریخ تولد"           , x: 110    , y: 198},
    { id: "relation2"       , value: "نسبت"                 , x: 75     , y: 198},
    { id: "cost2"           , value: "هزینه فرد"            , x: 33     , y: 198},
    
    { id: "fullName3"       , value: "نام و نام خانوادگی"   , x: 187    , y: 206},
    { id: "sponsorship3"    , value: "بلی"                  , x: 155    , y: 206},
    { id: "meliCode3"       , value: "کد ملی"               , x: 145    , y: 206},
    { id: "fatherName3"     , value: "نام پدر"              , x: 122    , y: 206},
    { id: "birthdayDate3"   , value: "تاریخ تولد"           , x: 110    , y: 206},
    { id: "relation3"       , value: "نسبت"                 , x: 75     , y: 206},
    { id: "cost3"           , value: "هزینه فرد"            , x: 33     , y: 206},
    
    { id: "fullName4"       , value: "نام و نام خانوادگی"   , x: 187    , y: 213},
    { id: "sponsorship4"    , value: "بلی"                  , x: 155    , y: 213},
    { id: "meliCode4"       , value: "کد ملی"               , x: 145    , y: 213},
    { id: "fatherName4"     , value: "نام پدر"              , x: 122    , y: 213},
    { id: "birthdayDate4"   , value: "تاریخ تولد"           , x: 110    , y: 213},
    { id: "relation4"       , value: "نسبت"                 , x: 75     , y: 213},
    { id: "cost4"           , value: "هزینه فرد"            , x: 33     , y: 213},
    
    { id: "fullName5"       , value: "نام و نام خانوادگی"   , x: 187    , y: 221},
    { id: "sponsorship5"    , value: "بلی"                  , x: 155    , y: 221},
    { id: "meliCode5"       , value: "کد ملی"               , x: 145    , y: 221},
    { id: "fatherName5"     , value: "نام پدر"              , x: 122    , y: 221},
    { id: "birthdayDate5"   , value: "تاریخ تولد"           , x: 110    , y: 221},
    { id: "relation5"       , value: "نسبت"                 , x: 75     , y: 221},
    { id: "cost5"           , value: "هزینه فرد"            , x: 33     , y: 221},
    // { id: "", value: "", x: 0, y: 0},
];

pdfModel.bank = [
    { id: "totalCostBank"   , value: "مبلغ کل"              , x: 190    , y: 78 },
    { id: "installments"    , value: "یازده ماه"            , x: 143    , y: 78 },
    { id: "eachInstallments", value: "قسط ماهیانه"          , x: 110    , y: 78 },
    { id: "firstInstallment", value: "اردیبهشت ماه"         , x: 75     , y: 78 },
    { id: "retCode"         , value: "شماره پرسنلی"         , x: 160    , y: 113},
    { id: "fullName"        , value: "نام و نام خانوادگی"   , x: 160    , y: 117},
    { id: "fatherName"      , value: "نام پدر"              , x: 110    , y: 117},
    { id: "shNum"           , value: "شماره شناسنامه"       , x: 62     , y: 117},
    { id: "meliCode"        , value: "کد ملی"               , x: 38     , y: 117},
    { id: "birthdayIssue"   , value: "محل صدور"             , x: 185    , y: 123},
    { id: "retPlace"        , value: "تامین اجتماعی"        , x: 140    , y: 123},
    { id: "address"         , value: "آدرس محل سکونت"       , x: 95     , y: 123},
    { id: "phoneNumber"     , value: "تلفن همراه"           , x: 145    , y: 128},
    { id: "refBank"         , value: "حساب رفاه"            , x: 65     , y: 145},
    // { id: "", value: "", x: 0, y: 0},
];

module.exports = pdfModel;