const pdfModel = {};

pdfModel.bimeh = [
    { id: "fullName"        , value: "نام و نام خانوادگی"   , x: 170    , y: 40 },
    { id: "fatherName"      , value: "نام پدر"              , x: 120    , y: 40 },
    { id: "shNum"           , value: "شماره شناسنامه"       , x: 75     , y: 40 },
    { id: "meliCode"        , value: "کد ملی"               , x: 50     , y: 40 },
    { id: "birthdayDate"    , value: "تاریخ تولد"           , x: 180    , y: 48 },
    { id: "birthdayPlace"   , value: "محل تولد"             , x: 135    , y: 48 },
    { id: "birthdayIssue"   , value: "محل صدور"             , x: 90     , y: 48 },
    { id: "retCode"         , value: "شماره پرسنلی"         , x: 38     , y: 48 },
    { id: "cost"            , value: "هزینه فرد"            , x: 175    , y: 56 },
    { id: "resBank"         , value: "حساب رسالت"           , x: 110    , y: 56 },
    { id: "workPlace"       , value: "محل خدمت"             , x: 58     , y: 56 },
    { id: "address"         , value: "آدرس محل سکونت"       , x: 170    , y: 62 },
    { id: "phoneNumber"     , value: "تلفن همراه"           , x: 48     , y: 62 },
    { id: "totalCost"       , value: "مبلغ کل"              , x: 80     , y: 240},
    { id: "signDate"        , value: "تاریخ امضا"           , x: 180    , y: 250},

    { id: "fullName1"       , value: "نام و نام خانوادگی"   , x: 187    , y: 194},
    { id: "sponsorship1"    , value: "بلی"                  , x: 155    , y: 194},
    { id: "meliCode1"       , value: "کد ملی"               , x: 145    , y: 194},
    { id: "fatherName1"     , value: "نام پدر"              , x: 122    , y: 194},
    { id: "birthdayDate1"   , value: "تاریخ تولد"           , x: 110    , y: 194},
    { id: "relation1"       , value: "نسبت"                 , x: 80     , y: 194},
    { id: "cost1"           , value: "هزینه فرد"            , x: 38     , y: 194},

    { id: "fullName2"       , value: "نام و نام خانوادگی"   , x: 187    , y: 202},
    { id: "sponsorship2"    , value: "بلی"                  , x: 155    , y: 202},
    { id: "meliCode2"       , value: "کد ملی"               , x: 145    , y: 202},
    { id: "fatherName2"     , value: "نام پدر"              , x: 122    , y: 202},
    { id: "birthdayDate2"   , value: "تاریخ تولد"           , x: 110    , y: 202},
    { id: "relation2"       , value: "نسبت"                 , x: 80     , y: 202},
    { id: "cost2"           , value: "هزینه فرد"            , x: 38     , y: 202},
    
    { id: "fullName3"       , value: "نام و نام خانوادگی"   , x: 187    , y: 210},
    { id: "sponsorship3"    , value: "بلی"                  , x: 155    , y: 210},
    { id: "meliCode3"       , value: "کد ملی"               , x: 145    , y: 210},
    { id: "fatherName3"     , value: "نام پدر"              , x: 122    , y: 210},
    { id: "birthdayDate3"   , value: "تاریخ تولد"           , x: 110    , y: 210},
    { id: "relation3"       , value: "نسبت"                 , x: 80     , y: 210},
    { id: "cost3"           , value: "هزینه فرد"            , x: 38     , y: 210},
    
    { id: "fullName4"       , value: "نام و نام خانوادگی"   , x: 187    , y: 217},
    { id: "sponsorship4"    , value: "بلی"                  , x: 155    , y: 217},
    { id: "meliCode4"       , value: "کد ملی"               , x: 145    , y: 217},
    { id: "fatherName4"     , value: "نام پدر"              , x: 122    , y: 217},
    { id: "birthdayDate4"   , value: "تاریخ تولد"           , x: 110    , y: 217},
    { id: "relation4"       , value: "نسبت"                 , x: 80     , y: 217},
    { id: "cost4"           , value: "هزینه فرد"            , x: 38     , y: 217},
    
    { id: "fullName5"       , value: "نام و نام خانوادگی"   , x: 187    , y: 225},
    { id: "sponsorship5"    , value: "بلی"                  , x: 155    , y: 225},
    { id: "meliCode5"       , value: "کد ملی"               , x: 145    , y: 225},
    { id: "fatherName5"     , value: "نام پدر"              , x: 122    , y: 225},
    { id: "birthdayDate5"   , value: "تاریخ تولد"           , x: 110    , y: 225},
    { id: "relation5"       , value: "نسبت"                 , x: 80     , y: 225},
    { id: "cost5"           , value: "هزینه فرد"            , x: 38     , y: 225},
    // { id: "", value: "", x: 0, y: 0},
];

pdfModel.bank = [
    { id: "totalCostBank"   , value: "مبلغ کل"              , x: 190    , y: 78 },
    { id: "installments"    , value: "یازده ماه"            , x: 143    , y: 78 },
    { id: "eachInstallments", value: "قسط ماهیانه"          , x: 110    , y: 78 },
    { id: "firstInstallment", value: "اردیبهشت ماه"         , x: 75     , y: 78 },
    { id: "retCode"         , value: "شماره پرسنلی"         , x: 160    , y: 110},
    { id: "fullName"        , value: "نام و نام خانوادگی"   , x: 160    , y: 117},
    { id: "fatherName"      , value: "نام پدر"              , x: 110    , y: 117},
    { id: "shNum"           , value: "شماره شناسنامه"       , x: 62     , y: 117},
    { id: "meliCode"        , value: "کد ملی"               , x: 38     , y: 117},
    { id: "birthdayIssue"   , value: "محل صدور"             , x: 185    , y: 123},
    { id: "retPlace"        , value: "تامین اجتماعی"        , x: 140    , y: 123},
    { id: "address"         , value: "آدرس محل سکونت"       , x: 90     , y: 123},
    { id: "phoneNum"        , value: "تلفن همراه"           , x: 145    , y: 128},
    { id: "refBank"         , value: "حساب رفاه"            , x: 65     , y: 145},
    // { id: "", value: "", x: 0, y: 0},
];

module.exports = pdfModel;